#!/bin/bash

FLASK_INIT_ROOT="$HOME/.flask-init"
SRC_FOLDER="${FLASK_INIT_ROOT}/src"

command=$1
arg=$2

case $command in
	"")
		{ ${SRC_FOLDER}/flask-init---version
		  ${SRC_FOLDER}/flask-init-help
		}
		;;
	"-h" | "--help" | "help")
		exec ${SRC_FOLDER}/flask-init-help
		;;
	"-v" | "--version" | "version")
		exec ${SRC_FOLDER}/flask-init---version
		;;
	"-p" | "--project" | "project")
		exec ${SRC_FOLDER}/flask-init-project ${2}
		;;
	*)
		echo "flask-init: no such command \`$command'"
		;;
esac
